version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0

    steps:
      - checkout

      - run:
          name: Build and Test
          command: mvn test

workflows:
  build_and_test:
    jobs:
      - build